apiVersion: v1
kind: Pod
metadata:
        name: gpu-test
spec:
        restartPolicy: Never
        containers:
                - name: pytorch
                  image: pytorch/pytorch
                  command:
                  - "/bin/sh"
                  - "-c"
                  args:
                  - cd ./minst1 && pwd && python3 main.py && echo "complete"
                  resources:
                          limits:
                                  nvidia.com/gpu: 1
                  volumeMounts:
                  - name: examples
                    mountPath: /workspace
                - name: pytorch2
                  image: pytorch/pytorch
                  command:
                  - "/bin/sh"
                  - "-c"
                  args:
                  - cd ./minst2 && pwd && python3 main.py && echo "complete"
                  resources:
                          limits:
                                  nvidia.com/gpu: 1
                  volumeMounts:
                  - name: examples
                    mountPath: /workspace
        volumes:
                - name: examples
                  hostPath:
                          path: /home/ubuntu/examples
                          type: Directory
        restartPolicy: OnFailure